version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
  admin:
    build: ./admin
    
    ports:
      - "5174:5174"
    restart: unless-stopped
